production:
  server: 
    port: 80
    timeout: 86400000
    bodySize: 50mb
    bypassCORS: false
    useHelmet: false
    httpOptionsOK: true
    servePackageInfo: true
    listenOnHttps: false
    enableHTTPBasicAuth: true
  default_render:
    view: {{DEFAULT_VIEW}}{{^DEFAULT_VIEW}}/index/view.html{{/DEFAULT_VIEW}}
    model: {{DEFAULT_MODEL}}{{^DEFAULT_MODEL}}/index/model.json{{/DEFAULT_MODEL}}
    controller: {{DEFAULT_CONTROLLER}}{{^DEFAULT_CONTROLLER}}/index/controller.js{{/DEFAULT_CONTROLLER}}
  log:
    level: info
    file: './logs/pro-logs.log' #Where log file will be saved. Date will be concatenated before the name.
    maxSize: 10000000 #(10MB) Maximum file log size, if one file reaches it, a new file is created.
    maxFiles: 30 # Max Files that can be created per day reaching the maxSize.
  auth:
    user: {{LOGIN_USER}}{{^LOGIN_USER}}governify-admin{{/LOGIN_USER}}
    password: {{LOGIN_PASSWORD}}{{^LOGIN_PASSWORD}}governify-project{{/LOGIN_PASSWORD}}

development:
  server: 
    port: 8080
    timeout: 86400000
    bodySize: 50mb
    bypassCORS: true
    useHelmet: true
    httpOptionsOK: true
    servePackageInfo: true
    listenOnHttps: false
    enableHTTPBasicAuth: true
  default_render:
    view: {{DEFAULT_VIEW}}{{^DEFAULT_VIEW}}/index/view.html{{/DEFAULT_VIEW}}
    model: {{DEFAULT_MODEL}}{{^DEFAULT_MODEL}}/index/model.json{{/DEFAULT_MODEL}}
    controller: {{DEFAULT_CONTROLLER}}{{^DEFAULT_CONTROLLER}}/index/controller.js{{/DEFAULT_CONTROLLER}}
  auth:
    user: {{LOGIN_USER}}{{^LOGIN_USER}}governify-admin{{/LOGIN_USER}}
    password: {{LOGIN_PASSWORD}}{{^LOGIN_PASSWORD}}governify-project{{/LOGIN_PASSWORD}}
  
  log:
    level: debug
    file: './logs/dev-logs.log' #Where log file will be saved. Date will be concatenated before the name.
    maxSize: 10000000 #(10MB) Maximum file log size, if one file reaches it, a new file is created.
    maxFiles: 30 # Max Files that can be created per day reaching the maxSize.

testing:
  server:
    port: 8080
    timeout: 86400000
    bodySize: 50mb
    bypassCORS: true
    useHelmet: true
    httpOptionsOK: true
    servePackageInfo: true
    listenOnHttps: false
    enableHTTPBasicAuth: false
  default_render:
    view: {{DEFAULT_VIEW}}{{^DEFAULT_VIEW}}/index/view.html{{/DEFAULT_VIEW}}
    model: {{DEFAULT_MODEL}}{{^DEFAULT_MODEL}}/index/model.json{{/DEFAULT_MODEL}}
    controller: {{DEFAULT_CONTROLLER}}{{^DEFAULT_CONTROLLER}}/index/controller.js{{/DEFAULT_CONTROLLER}}

  auth:
    user: {{LOGIN_USER}}{{^LOGIN_USER}}governify-admin{{/LOGIN_USER}}
    password: {{LOGIN_PASSWORD}}{{^LOGIN_PASSWORD}}governify-project{{/LOGIN_PASSWORD}}
  log:
    file: './logs/test-logs.log' #Where log file will be saved. Date will be concatenated before the name.
    maxSize: 10000000 #(10MB) Maximum file log size, if one file reaches it, a new file is created.
    maxFiles: 30 # Max Files that can be created per day reaching the maxSize.
  
